## 1. Introducción

##### hola

## 2. Importación de librerias

In [19]:
import pandas as pd
import numpy as np

from pathlib import Path

import matplotlib.pyplot as plt

## 3. Carga de datos

In [21]:
RUTA = Path("./Data")

dim_conductor = pd.read_csv(RUTA / "dim_conductor.csv")
dim_depot = pd.read_csv(RUTA / "dim_depot.csv")
dim_linea = pd.read_csv(RUTA / "dim_linea.csv")
dim_parada = pd.read_csv(RUTA / "dim_parada.csv")
dim_tarifa = pd.read_csv(RUTA / "dim_tarifa.csv")
dim_vehiculo = pd.read_csv(RUTA / "dim_vehiculo.csv")

fact_incidencias = pd.read_csv(RUTA / "fact_incidencias.csv")
fact_mantenimiento = pd.read_csv(RUTA / "fact_mantenimiento.csv")
fact_viajes = pd.read_csv(RUTA / "fact_viajes.csv")

In [28]:
print(dim_conductor.shape)

display(dim_conductor.head())

dim_conductor.info()

(30, 1)

  conductor_id;nombre;anno_incorporacion;antiguedad_anos;turno_habitual;depot_id;formacion;licencia_tipo;activo;ausencias_2024;;;
0  1;Carlos Garcia;2009;15;Partido;3;Basica;D;VER...
1  2;Maria Lopez;2013;11;Noche (22-06h);1;Basica;...
2  3;Juan Martinez;2008;16;Manana (06-14h);2;Comp...
3  4;Ana Fernandez;2007;17;manana;1;Basica + Arti...
4  5;Pedro Sanchez;2016;8;Partido;3;Basica + Arti...

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 1 columns):
 #   Column                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                           --------------  -----
 0   conductor_id;nombre;anno_incorporacion;antiguedad_anos;turno_habitual;depot_id;formacion;licencia_tipo;activo;ausencias_2024;;;  30 non-null     str
dtypes: str(1)
memory usage: 2.5 KB

In [27]:
print(dim_depot.shape)

display(dim_depot.head())

dim_depot.info()

(3, 6)

,depot_id,nombre,barrio,latitud,longitud,capacidad_vehiculos
0,1,Cochera Norte,Barrio Norte,40.440,-3.720,20
1,2,Cochera Central,Centro,40.418,-3.700,15
2,3,Cochera Sur,Barrio Sur,40.395,-3.695,12

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   depot_id             3 non-null      int64
 1   nombre               3 non-null      str
 2   barrio               3 non-null      str
 3   latitud              3 non-null      float64
 4   longitud             3 non-null      float64
 5   capacidad_vehiculos  3 non-null      int64
dtypes: float64(2), int64(2), str(2)
memory usage: 343.0 bytes

## 4. Exploración inicial

### - dimensiones

### - tipos

### - primeras filas

## 5. Calidad de datos

### - valores nulos

### - duplicados

### - tipos incorrectos

## 6. Análisis estadistico

## 7. Outliers

## 8. Visualizaciones

## 9. conclusiones